name: BurgsAndBanners
version: 0.1.6
main: com.brandon.burgsbanners.BurgsAndBannersPlugin
api-version: "1.21"

depend: [MultiPolarCurrency]
softdepend: [dynmap]


commands:
  burg:
    description: Burg & Banner civic command
    usage: /burg found <name> <currencyCode>
  city:
    description: Alias for /burg
    usage: /city found <name> <currencyCode>

permissions:
  burg.*:
    default: op
    children:
      burg.found: true
      burg.info: true
      burg.treasury: true
      burg.claim: true
      burg.unclaim: true

  burg.found:
    default: op

  burg.info:
    default: true

  burg.treasury:
    default: true

  burg.claim:
    default: op

  burg.unclaim:
    default: op
